export const COMMON_SCHOOLS = [
  "Cambridge International School",
  "Delhi Public School",
  "St. Xavier's High School",
  "Ryan International School",
  "Kendriya Vidyalaya",
  "The Doon School",
  "La Martiniere College",
  "Modern School",
  "Bishop Cotton School",
  "Loyola School",
  "Greenwood High",
  "Oakridge International",
  "National Public School",
  "Bombay Scottish School",
  "Springdales School",
  "Vidya Mandir",
  "Harvard University",
  "Stanford University",
  "MIT",
  "University of Oxford",
  "University of Cambridge",
  "Indian Institute of Technology",
  "University of Dhaka",
  "BUET",
  "University of California, Berkeley",
];