/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAiCoverImageRouteImport } from './routes/api/ai-cover-image'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAiCoverImageRoute = ApiAiCoverImageRouteImport.update({
  id: '/api/ai-cover-image',
  path: '/api/ai-cover-image',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/api/ai-cover-image': typeof ApiAiCoverImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/api/ai-cover-image': typeof ApiAiCoverImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/create': typeof CreateRoute
  '/dashboard': typeof DashboardRoute
  '/api/ai-cover-image': typeof ApiAiCoverImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/create' | '/dashboard' | '/api/ai-cover-image'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/create' | '/dashboard' | '/api/ai-cover-image'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/create'
    | '/dashboard'
    | '/api/ai-cover-image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CreateRoute: typeof CreateRoute
  DashboardRoute: typeof DashboardRoute
  ApiAiCoverImageRoute: typeof ApiAiCoverImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ai-cover-image': {
      id: '/api/ai-cover-image'
      path: '/api/ai-cover-image'
      fullPath: '/api/ai-cover-image'
      preLoaderRoute: typeof ApiAiCoverImageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CreateRoute: CreateRoute,
  DashboardRoute: DashboardRoute,
  ApiAiCoverImageRoute: ApiAiCoverImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
